### ISSUE TITLE
Does not compile under Visual Studio 2019 with C++20

### ISSUE THREAD

**Issue by Warwolt** [emil-e/rapidcheck#266]
Hi! 

When compiling this project under MSVC 2019 with the standard set to C++20, the `Seq.h` header fails with error:

```
Seq.h(37,45): error C2653: 'result_of': is not a class or namespace name 
```

`result_of` was depricated in C++17 and has been removed in C++20, and according to [notes on cppreference](https://en.cppreference.com/w/cpp/types/result_of#Notes) the preferred alternative is to use `invoke_result`.

**Comment by Warwolt** [comment]
Just saw that this could potentially be addressed by #261 if it becomes accepted.

**Comment by objectx** [comment]
Still unable to build correctly on MSVC.  The rapidcheck uses the `__cplusplus` value to [switch the definition](https://github.com/emil-e/rapidcheck/blob/de19dd0a8d2e712111d9b6dde8a40b64afbfc245/include/rapidcheck/Compat.hpp#L8). But MSVC's `__cplusplus` macro value does not reflect the language level [without the `/Zc:__cplusplus` option](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160).  To build correctly, add the `/Zc:__cplusplus` as a CMake's public target property like `target_compile_options (rapidcheck PUBLIC /Z:__cplusplus)`

**Comment by objectx** [comment]
To correctly reflect the language level to `__cplusplus` for MSVC、We must supply the [`/Zc:__cplusplus` option](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160). Otherwise `__cplusplus == 199711L` 😞

**Comment by Warwolt** [comment]
I could build this using MSVC with C++20, closing this issue.
